# Weather card for vedur.is (2022-11-29)
# Author: Kristján Bjarni Guðmundsson
# https://github.com/kristjanbjarni/home-assistant-packages

shell_command:
  vedur_curl: 'curl {{url}} -s -S -f -o {{output}}'
  
input_number:
  vedur_vedurstod:
    name: Veður.is - Veðurstöð
    min: 1
    max: 99999
    step: 1
    mode: box
    icon: mdi:weather-cloudy

automation:
  - alias: 'Veður: Veðurspá/Textaspá/Norðurljós skyndiminni'
    trigger:
    - platform: time_pattern
      hours: /1
    action:
    - service: shell_command.vedur_curl
      data:
        url: https://xmlweather.vedur.is/?op_w=xml&type=txt&lang=is&view=xml&ids=3;6
        output: /config/www/vedur_is/texts.xml
    - service: shell_command.vedur_curl
      data:
        url: https://xmlweather.vedur.is/?op_w=xml&type=forec&lang=is&view=xml&ids={{ states('input_number.vedur_vedurstod') | int(1) }}
        output: /config/www/vedur_is/forecasts.xml
    - service: shell_command.vedur_curl
      data:
        url: https://xmlweather.vedur.is/aurora?op=xml&type=index
        output: /config/www/vedur_is/aurora.xml
  - alias: 'Veður: Veðurathuganir skyndiminni'
    trigger:
    - platform: time_pattern
      minutes: /10
    action:
    - service: shell_command.vedur_curl
      data:
        url: https://xmlweather.vedur.is/?op_w=xml&view=xml&type=obs&ids={{ states('input_number.vedur_vedurstod') | int(1) }}&lang=is&params=T;F;D;W;V;RH;P
        output: /config/www/vedur_is/observations.xml

sensor vedur condition lookup:
  platform: template
  sensors:
    vedur_condition_lookup:
      value_template: "OK"
      attribute_templates:
        condition: >
          {% set vedur_condition = {'Skýjað':'cloudy',
                                'Alskýjað':'cloudy',
                                'Skýstrókar':'exceptional',
                                'Þoka':'fog',
                                'Hagl':'hail',
                                'Þrumuveður':'lightning',
                                'Lítils háttar þrumuveður':'lightning-rainy',
                                'Léttskýjað':'partlycloudy',
                                'Rigning':'pouring',
                                'Skúrir':'rainy',
                                'Súld':'rainy',
                                'Lítils háttar súld':'rainy',
                                'Lítils háttar rigning':'rainy',
                                'Snjókoma':'snowy',
                                'Snjóél':'snowy',
                                'Skafrenningur':'snowy',
                                'Lítils háttar snjókoma':'snowy',
                                'Slydda':'snowy-rainy',
                                'Slydduél':'snowy-rainy',
                                'Frostrigning':'snowy-rainy',
                                'Lítils háttar slydda':'snowy-rainy',
                                'Heiðskírt':'sunny',
                                'Moldrok':'windy'
                               } %}
          {{ vedur_condition }}
    vedur_aurora_lookup:
      value_template: "OK"
      attribute_templates:
        condition: >
          {% set list = ['Lágmarksvirkni','Mjög lítil virkni','Lítil virkni','Dálítil virkni','Talsverð virkni','Allmikil virkni','Mikil virkni','Öflug virkni','Mjög öflug virkni','Hámarksvirkni'] %}
          {{ list }}          

sensor vedur:
  platform: rest
  name: vedur
  resource: http://localhost:8123/local/vedur_is/observations.xml
  json_attributes_path: "$.observations.station"
  json_attributes:
    - T
    - F
    - D
    - W
    - V
    - RH
    - P
  value_template: "{{value_json.observations.station.name}}"
  scan_interval: 60

sensor vedur forecast source:
  platform: rest
  name: vedur_forecast_source
  resource: http://localhost:8123/local/vedur_is/forecasts.xml
  json_attributes_path: "$.forecasts.station"
  json_attributes:
    - forecast
  value_template: "{{value_json.forecasts.station.name}}"
  scan_interval: 300
  
sensor vedur aurora source:
  platform: rest
  name: vedur_aurora_source
  resource: http://localhost:8123/local/vedur_is/aurora.xml
  json_attributes_path: "$.aurora"
  json_attributes:
    - night_data
  value_template: "OK"
  scan_interval: 300  
  
sensor vedur text source:
  platform: rest
  name: vedur_text_source
  resource: http://localhost:8123/local/vedur_is/texts.xml
  json_attributes_path: "$.texts"
  json_attributes:
    - text
  value_template: "{{value_json.texts.text[0].title}}"
  scan_interval: 300
  
sensor vedur forecast:
  platform: template
  sensors:
    vedur_forecast:
      friendly_name: "Veðurspá"
      value_template: "OK"
      icon_template: "mdi:weather-cloudy"
      attribute_templates:
        current: >
          {% set now = now().timestamp() %}
          {% set work = namespace(data=none,break=false) %}
          {% for f in state_attr('sensor.vedur_forecast_source','forecast') if not work.break  %}
            {% set cur_datetime = as_timestamp(strptime(f.ftime,'%Y-%m-%d %H:%M:%S')) %}
            {% if cur_datetime >= now %}
              {% set data = {'datetime': f.ftime, 
                             'condition': f.W,
                             'temperature': float(f.T),
                             'wind_speed': float(f.F)
                            } %}
              {% set work.data=data %}
              {% set work.break = true %}
            {% endif %}
          {% endfor %}
          {{ work.data }}
        forecast: >
          {% set forecasts = namespace(items=[]) %}
          {% set work = namespace(date=none,time=none,temp=none,templow=none,wind=none,cond=none) %}
          {% for f in state_attr('sensor.vedur_forecast_source','forecast') %}
            {% set cur_date = f.ftime[0:10] %}
            {% set cur_time = f.ftime[11:13] %}
            {% set cur_temp = float(f.T) %}
            {% set cur_cond = f.W %}
            {% set cur_wind = float(f.F) %}
            {%if work.date is none %}
              {% set work.date = cur_date %}
              {% set work.time = cur_time %}
              {% set work.temp = cur_temp %}
              {% set work.templow = cur_temp %}
              {% set work.cond = cur_cond %}
              {% set work.wind = cur_wind %}
            {% endif %}
            {% if cur_date == work.date %}
              {% if cur_temp < work.templow %}
                {% set work.templow = cur_temp %}
              {% endif %}
              {% if cur_temp > work.temp %}
                {% set work.temp = cur_temp %}
              {% endif %}
              {% if cur_time == '12' %}
                {% set work.time = cur_time %}
                {% set work.cond = cur_cond %}
                {% set work.wind = cur_wind %}
              {% endif %}
            {% else %}
                {% set cond = none %}
                {% if state_attr('sensor.vedur_condition_lookup','condition') %}
                  {% set cond = state_attr('sensor.vedur_condition_lookup','condition').get(work.cond) %}
                {% endif %}
                {% set data = {'datetime': work.date+'T'+work.time+':00:00Z', 
                             'condition': cond,
                             'temperature': work.temp,
                             'wind_speed': work.wind,
                             'templow': work.templow } %}
              {% set forecasts.items = forecasts.items + [data] %}
              {% set work.date = cur_date %}
              {% set work.time = cur_time %}
              {% set work.temp = cur_temp %}
              {% set work.templow = cur_temp %}
              {% set work.cond = cur_cond %}
              {% set work.wind = cur_wind %}
            {% endif %}
          {% endfor %}
          {% if work.date is not none %}
            {% set cond = none %}
            {% if state_attr('sensor.vedur_condition_lookup','condition') %}
              {% set cond = state_attr('sensor.vedur_condition_lookup','condition').get(work.cond) %}
            {% endif %}
            {% set data = {'datetime': work.date+'T'+work.time+':00:00Z', 
                           'condition': cond,
                           'temperature': work.temp,
                           'wind_speed': work.wind ,
                           'templow': work.templow } %}
            {% set forecasts.items = forecasts.items + [data] %}
          {% endif %}
          {{ forecasts.items }}

sensor vedur sensors:
  platform: template
  sensors:
    vedur_temperature:
      friendly_name: "Hitastig"
      value_template: >
        {% if state_attr('sensor.vedur','T') %}
          {{ state_attr('sensor.vedur','T' ) | replace(',','.') | float(0) }}
        {% else %}
          {{ state_attr('sensor.vedur_forecast','current').temperature | float(0) }}
        {% endif %}
      device_class: temperature
      unit_of_measurement: "°C"
    vedur_wind_speed:
      friendly_name: "Vindhraði"
      value_template: >
        {% if state_attr('sensor.vedur','F') %}
          {{ state_attr('sensor.vedur','F') | replace(',','.') | float(0) }}
        {% else %}
          {{ state_attr('sensor.vedur_forecast','current').wind_speed | float(0) }}
        {% endif %}
      unit_of_measurement: "m/s"
      icon_template: "mdi:weather-windy"
    vedur_wind_bearing:
      friendly_name: "Vindátt"
      value_template: >
        {% if state_attr('sensor.vedur','D') %}
          {{ state_attr('sensor.vedur','D' ) }}
        {% else %}
          {{ state_attr('sensor.vedur_forecast','current').wind_bearing | default('') }}
        {% endif %}
      icon_template: "mdi:windsock"
    vedur_condition_org:
      friendly_name: "Veðurlýsing (Original)"
      value_template: >
        {% if state_attr('sensor.vedur','W') %}
          {{ state_attr('sensor.vedur','W') }}
        {% else %}          
          {{ state_attr('sensor.vedur_forecast','current').condition }}
        {% endif %}
      icon_template: "mdi:weather-cloudy"
    vedur_condition:
      friendly_name: "Veðurlýsing"
      value_template: >
        {% set cond = states('sensor.vedur_condition_org') %}
        {{ state_attr('sensor.vedur_condition_lookup','condition').get(cond) }}
      icon_template: "mdi:weather-cloudy"
    vedur_visibility:
      friendly_name: "Skyggni"
      value_template: "{{ state_attr('sensor.vedur','V') | replace('>','') | replace(',','.') | float(0) }}"
      icon_template: "mdi:weather-cloudy"
    vedur_humidity:
      friendly_name: "Rakastig"
      value_template: "{{ state_attr('sensor.vedur','RH') | replace(',','.') | float(0) }}"
      device_class: temperature
      unit_of_measurement: "%"
    vedur_pressure:
      friendly_name: "Loftþrýstingur"
      value_template: "{{ state_attr('sensor.vedur','P') | replace(',','.') | float(0)  }}"
      device_class: pressure
      unit_of_measurement: "hPa"
    vedur_text_capital:
      value_template: "Veðurhorfur á höfuðborgarsvæðinu"
      icon_template: "mdi:weather-cloudy"
      attribute_templates:
        text: >
          {% set node = state_attr('sensor.vedur_text_source','text') | selectattr('@id','equalto','3') | first %}
          {% if node is not none %}
            {% set text = node.content %}
            {% if text["#text"] == null %}
              {{ text }}
            {% else %}
              {{ text["#text"] }}
            {% endif %}
          {% endif %}
    vedur_text_country:
      value_template: "Veðurhorfur á landinu næstu daga"
      icon_template: "mdi:weather-cloudy"
      attribute_templates:
        text: >
          {% set node = state_attr('sensor.vedur_text_source','text') | selectattr('@id','equalto','6') | first %}
          {% if node is not none %}
            {% set text = node.content %}
            {% if text["#text"] == null %}
              {{ text }}
            {% else %}
              {{ text["#text"] }}
            {% endif %}
          {% endif %}
    vedur_aurora_base:
      value_template: >
        {% set data = state_attr('sensor.vedur_aurora_source','night_data') %}
        {% if data %}
          {{ data[0].activity_forecast | int(0) }}
        {% else %}
          {{ 0 | int }}
        {% endif %}
      attribute_templates:
        icon: >
          {% set data = state_attr('sensor.vedur_aurora_source','night_data') %}
          {% if data %}
            {% set n = data[0].activity_forecast | int(0) %}
            {% if n > 5 %}
              mdi:weather-night
            {% elif n > 2 %}
              mdi:weather-night-partly-cloudy
            {% else %}
              mdi:weather-cloudy
            {% endif %}            
          {% else %}
            mdi:weather-cloudy
          {% endif %}
    vedur_aurora:
      friendly_name: "Norðurljós"
      value_template: "{{ states('sensor.vedur_aurora_base') | int(0) }}"
      icon_template: "{{ state_attr('sensor.vedur_aurora_base','icon') }}"
      attribute_templates:
        text: >
          {% set condition = state_attr('sensor.vedur_aurora_lookup','condition') %}
          {% set n = states('sensor.vedur_aurora_base') | int(0) %}
          {% if n and condition %}
            {{ condition[n] }}
          {% else %}
            none
          {% endif %}          
        forecast: >
          {%- set condition = state_attr('sensor.vedur_aurora_lookup','condition') %}
          |Dags|Spá|
          
          |:---|:---|
          
          {%- for data in state_attr('sensor.vedur_aurora_source','night_data') %}
            {%- set date = strptime(data.evening_date,'%Y-%m-%d') %}
            {%- set d = date.strftime('%a. %d. %b') %}
            {%- set n = data.activity_forecast | int(0) %}
            {%- set c = condition[n] %}
          |{{d}}|{{c}} ({{n}})|
            
          {%- endfor %}
    vedur_aurora_text:
      friendly_name: "Norðurljós"
      icon_template: "{{ state_attr('sensor.vedur_aurora_base','icon') }}"
      value_template: >
        {% set condition = state_attr('sensor.vedur_aurora_lookup','condition') %}
        {% set n = states('sensor.vedur_aurora_base') | int(0) %}
        {% if n and condition %}
          {{ condition[n] }}
        {% else %}
          none
        {% endif %}

weather:
  - platform: template
    name: "Veður.is"
    attribution_template: "Gögn frá Veður.is"
    condition_template: "{{ states('sensor.vedur_condition') }}"
    temperature_template: "{{ states('sensor.vedur_temperature') | float(0) }}"
    humidity_template: "{{ states('sensor.vedur_humidity') | float(0) }}"
    pressure_template: "{{ states('sensor.vedur_pressure') | float(0) }}"
    wind_speed_template: "{{ states('sensor.vedur_wind_speed') | float(0) }}"
    wind_bearing_template: "{{ states('sensor.vedur_wind_bearing') }}"
    visibility_template: "{{ states('sensor.vedur_visibility') | float(0) }}"
    forecast_template: "{{ state_attr('sensor.vedur_forecast','forecast') }}"
